
{% set data = load_setup_py_data() %}


package:
    name    : highbeams

    version : {{ data.get('version') }}


source:
    path: ..

build:
    number: 1
    noarch: python

requirements:
    build:
      - python >=3.11
      - setuptools

    run:
      - python >=3.11

test:
    imports:
      - highbeams

    requires:
      - pytest

about:
  home: https://github.com/spc-group/highbeams
  license: All rights reserved
  summary: Change LED strip to respond to PV states.
